CREATE DATABASE CustomerShoppingDB;
USE CustomerShoppingDB;

SELECT *
FROM CustomerShopping;



-- Q1. What is the total revenue generated by male vs. female customers?

SELECT
    Gender,
    SUM([Purchase Amount (USD)]) AS Total_Revenue
FROM CustomerShopping
GROUP BY Gender
ORDER BY Total_Revenue DESC;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT
    [Customer ID],
    [Purchase Amount (USD)]
FROM CustomerShopping
WHERE [Discount Applied] = 'Yes'
  AND [Purchase Amount (USD)] >=
      (SELECT AVG([Purchase Amount (USD)])
       FROM CustomerShopping)
ORDER BY [Purchase Amount (USD)] DESC;


-- Q3. What are the top 5 products with the highest average review rating?

SELECT TOP 5
    [Item Purchased],
    ROUND(AVG([Review Rating]), 2) AS Average_Product_Rating
FROM CustomerShopping
GROUP BY [Item Purchased]
ORDER BY Average_Product_Rating DESC;


-- Q4. Compare the average purchase amounts between Standard and Express Shipping.

SELECT
    [Shipping Type],
    ROUND(AVG([Purchase Amount (USD)]), 2) AS Average_Purchase
FROM CustomerShopping
WHERE [Shipping Type] IN ('Standard', 'Express')
GROUP BY [Shipping Type];


-- Q5. Do subscribed customers spend more?
-- Compare average spending and total revenue.

SELECT
    [Subscription Status],
    COUNT([Customer ID]) AS Total_Customers,
    ROUND(AVG([Purchase Amount (USD)]), 2) AS Average_Spend,
    ROUND(SUM([Purchase Amount (USD)]), 2) AS Total_Revenue
FROM CustomerShopping
GROUP BY [Subscription Status]
ORDER BY Total_Revenue DESC, Average_Spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases
-- with discounts applied?

SELECT TOP 5
    [Item Purchased],
    ROUND(
        SUM(CASE
                WHEN [Discount Applied] = 'Yes' THEN 1
                ELSE 0
            END) * 100.0 / COUNT(*), 2
    ) AS Discount_Rate
FROM CustomerShopping
GROUP BY [Item Purchased]
ORDER BY Discount_Rate DESC;


-- Q7. Which category generates the highest total revenue?

SELECT TOP 1
    Category,
    ROUND(SUM([Purchase Amount (USD)]), 2) AS Total_Revenue
FROM CustomerShopping
GROUP BY Category
ORDER BY Total_Revenue DESC;


-- Q8. Which are the top 5 most frequently purchased products?

SELECT TOP 5
    [Item Purchased],
    COUNT(*) AS Number_of_Purchases
FROM CustomerShopping
GROUP BY [Item Purchased]
ORDER BY Number_of_Purchases DESC;


-- Q9. Which season generates the highest revenue?

SELECT TOP 1
    Season,
    ROUND(SUM([Purchase Amount (USD)]), 2) AS Total_Revenue
FROM CustomerShopping
GROUP BY Season
ORDER BY Total_Revenue DESC;


-- Q10. What is the average purchase amount for customers
-- who used a promo code vs. those who did not?

SELECT
    [Promo Code Used],
    COUNT(*) AS Total_Purchases,
    ROUND(AVG([Purchase Amount (USD)]), 2) AS Average_Purchase
FROM CustomerShopping
GROUP BY [Promo Code Used];


-- Q11. Which payment method is most commonly used?

SELECT TOP 1
    [Payment Method],
    COUNT(*) AS Number_of_Transactions
FROM CustomerShopping
GROUP BY [Payment Method]
ORDER BY Number_of_Transactions DESC;


-- Q12. Which category has the highest average customer rating?

SELECT TOP 1
    Category,
    ROUND(AVG([Review Rating]), 2) AS Average_Rating
FROM CustomerShopping
GROUP BY Category
ORDER BY Average_Rating DESC;


-- Q13. Which products have an average rating below 3.5?

SELECT
    [Item Purchased],
    ROUND(AVG([Review Rating]), 2) AS Average_Rating,
    COUNT(*) AS Total_Purchases
FROM CustomerShopping
GROUP BY [Item Purchased]
HAVING AVG([Review Rating]) < 3.5
ORDER BY Average_Rating ASC;


-- Q14. Which locations generate the highest revenue?

SELECT TOP 10
    Location,
    COUNT(*) AS Total_Purchases,
    ROUND(SUM([Purchase Amount (USD)]), 2) AS Total_Revenue
FROM CustomerShopping
GROUP BY Location
ORDER BY Total_Revenue DESC;


-- Q15. How does customer loyalty affect spending?

SELECT
    CASE
        WHEN [Previous Purchases] = 0 THEN 'New Customer'
        WHEN [Previous Purchases] BETWEEN 1 AND 5 THEN 'Occasional Customer'
        WHEN [Previous Purchases] BETWEEN 6 AND 10 THEN 'Regular Customer'
        ELSE 'Loyal Customer'
    END AS Customer_Type,

    COUNT(*) AS Number_of_Customers,
    ROUND(AVG([Purchase Amount (USD)]), 2) AS Average_Spend,
    ROUND(SUM([Purchase Amount (USD)]), 2) AS Total_Revenue

FROM CustomerShopping

GROUP BY
    CASE
        WHEN [Previous Purchases] = 0 THEN 'New Customer'
        WHEN [Previous Purchases] BETWEEN 1 AND 5 THEN 'Occasional Customer'
        WHEN [Previous Purchases] BETWEEN 6 AND 10 THEN 'Regular Customer'
        ELSE 'Loyal Customer'
    END

ORDER BY Total_Revenue DESC;


-- Q16. What percentage of total revenue comes from each category?

SELECT
    Category,
    ROUND(SUM([Purchase Amount (USD)]), 2) AS Revenue,

    ROUND(
        SUM([Purchase Amount (USD)]) * 100.0 /
        SUM(SUM([Purchase Amount (USD)])) OVER (), 2
    ) AS Revenue_Percentage

FROM CustomerShopping

GROUP BY Category

ORDER BY Revenue DESC;


-- Q17. What are the overall business KPIs?

SELECT
    COUNT(*) AS Total_Orders,
    COUNT(DISTINCT [Customer ID]) AS Unique_Customers,
    ROUND(SUM([Purchase Amount (USD)]), 2) AS Total_Revenue,
    ROUND(AVG([Purchase Amount (USD)]), 2) AS Average_Order_Value,
    ROUND(AVG([Review Rating]), 2) AS Average_Rating

FROM CustomerShopping;


-- Q18. Rank product categories based on total revenue.

SELECT
    Category,
    ROUND(SUM([Purchase Amount (USD)]), 2) AS Total_Revenue,

    RANK() OVER (
        ORDER BY SUM([Purchase Amount (USD)]) DESC
    ) AS Revenue_Rank

FROM CustomerShopping

GROUP BY Category;